version: 2.1
jobs:
  deploy:
    machine:
      image: 'circleci/classic:latest'
    steps:
      - checkout
      - run: echo "Start Deploy"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd ~/remainder && git pull origin master'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
         filters:
           branches:
            only: /master\/.*/